### ISSUE TITLE
renaming webgl to uni-gl

### ISSUE THREAD

**Issue by jice-nospam** [unrust/uni-gl#2]
oussama/webgl is already published on crates.io.

Shall I rename this project uni-gl ?

**Comment by edwin0cheng** [comment]
Oh... that's unfortunate. Rename it then. 
Do you know any other crates have this problems too ?

**Comment by jice-nospam** [comment]
nah there's no uni-* or unrust crate yet. Ok I'll publish uni-gl asap, then I'll send a PR to upgrade unrust

**Comment by edwin0cheng** [comment]
Do you want to rename the github repository too ? I can do that now?

**Comment by edwin0cheng** [comment]
@jice-nospam  The github repository is renamed.

**Comment by jice-nospam** [comment]
thanks :)
